// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZBOcpAOE-lgI8Ov6p0BJVodU4tghK13g',
    appId: '1:14854092024:web:a643b7213da7bd2a22770d',
    messagingSenderId: '14854092024',
    projectId: 'myproject2-6d698',
    authDomain: 'myproject2-6d698.firebaseapp.com',
    storageBucket: 'myproject2-6d698.appspot.com',
    measurementId: 'G-SNC9PH3VTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIquMse_AqJyNlupisWZucI9AfrbtrQJQ',
    appId: '1:14854092024:android:5cc056ff0abc765b22770d',
    messagingSenderId: '14854092024',
    projectId: 'myproject2-6d698',
    storageBucket: 'myproject2-6d698.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqdWC_BVmKTvcamyjuU8shBnS28wsMpog',
    appId: '1:14854092024:ios:fb946a61645bdc4022770d',
    messagingSenderId: '14854092024',
    projectId: 'myproject2-6d698',
    storageBucket: 'myproject2-6d698.appspot.com',
    iosBundleId: 'com.example.mobile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqdWC_BVmKTvcamyjuU8shBnS28wsMpog',
    appId: '1:14854092024:ios:bcaf555008d6746422770d',
    messagingSenderId: '14854092024',
    projectId: 'myproject2-6d698',
    storageBucket: 'myproject2-6d698.appspot.com',
    iosBundleId: 'com.example.mobile2.RunnerTests',
  );
}
